version: '3.8'

services:
  vite-app:
    image: web-frontend:dev
    working_dir: /app
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
     - CHOKIDAR_USEPOLLING=true
    